## config.py
TELEGRAM_TOKEN = "YOUR_TELEGRAM_BOT_TOKEN"
UNIVERSITY_URL = "UNIVERSITY_PORTAL_URL"
TESSERACT_PATH = r"YOUR_TESSERACT_INSTALLATION_PATH"
DATA_DIR = "data"

STUDENTS = [
    {
        "id": "STUDENT_ID",
        "password": "STUDENT_PASSWORD",
        "chat_id": "STUDENT_TELEGRAM_CHAT_ID"
    }
]