FROM python:3.10-slim

# ۱. نصب تسرکت و ابزارهای مورد نیاز لینوکس
RUN apt-get update && apt-get install -y \
    wget \
    gnupg \
    unzip \
    tesseract-ocr \
    tesseract-ocr-eng \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# ۲. دانلود و نصب مستقیم گوگل کروم نسخه پایدار
RUN wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
    && apt-get update \
    && apt-get install -y ./google-chrome-stable_current_amd64.deb \
    && rm google-chrome-stable_current_amd64.deb

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD ["python", "main.py"]
